Upgraded NetApp SDK to latest version 1.13.0
Azure-Samples/netappfiles-dotnetcore-nfs4.1-sdk-sample pull request #1
Opened 2021-09-03 03:40 UTC by AdelGhabboun

1- Upgraded SDK to latest version 1.13.0
2- Activated the cleanup code with a flag
3- Added the waiting logic after creation and deletion

2021-09-08 13:59 UTC, hildurhodd approved these changes
LGTM

2021-09-15 15:47 UTC, paulomarquesc commented
> 

The cleanup is not controlled through a variable, please change the readme comments to address the changes.

---
Refers to: README.md:24 in bea9d78. [](commit_id = bea9d78b2cfc75bbd6dc68f895a442a85a19d643, deletion_comment = False)

2021-09-15 15:47 UTC, paulomarquesc requested changes
:clock1:

2021-09-15 15:49 UTC, paulomarquesc commented on CHANGELOG.md
> +[1.0.0 (2021-09-02)](#1.0.1 (2021-09-02))
>1.0.0 [](http://example.com/codeflow?start=1&length=5)

This version needs to be updated.

2021-09-15 15:49 UTC, paulomarquesc commented on CHANGELOG.md
Version and date needs to be updated

2021-09-15 20:51 UTC, paulomarquesc approved these changes
:shipit:

2021-09-15 21:04 UTC, merged